name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/gradle-build.yml@main
