name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle build and publish
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.PLUGIN_PORTAL_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.PLUGIN_PORTAL_SECRET }}
        with:
          arguments: publishPlugins
